# Landing Zone for Data

AWSTemplateFormatVersion: 2010-09-09
Description: Secrets for running the orchestrator

Parameters:
  kinesisStreamName:
    Type : String
  dynamoDBTableName:
    Type : String
  ecsClusterName: 
    Type: String
  taskDefinitionARN:
    Type: String
  vpcID:
    Type: String
  s3BucketName:
    Type: String

Resources:
  twitterAPISecretsParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /prod/twitter
      Type: String
      Value: !Sub
        - '{"CONSUMER_KEY": "${consumerKey}", "CONSUMER_SECRET":"${consumerSecret}", "ACCESS_TOKEN_KEY":"${accessTokenKey}", "ACCESS_TOKEN_SECRET":"${accessTokenSecret}","RECORD_COUNT":${recordCount}}'
        - consumerKey: "dsfsdf"
          consumerSecret: "2324"
          accessTokenKey: "3323"
          accessTokenSecret: "3323"
          recordCount: 1000
      Description: Twitter API Secrets

  twitterDependencyVariablesParam:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: Twitter Collector Dependencies
      Name: /prod/twitter/dependencies
      Type: String
      Value: !Sub
        - '{ "S3_BUCKET": "${s3Bucket}", "TRACK_TABLE":"${trackTable}","VPC_ID":"${vpcID}"}'
        - trackTable: !Ref dynamoDBTableName
          s3Bucket: !Ref s3BucketName
          vpcID: !Ref vpcID

