AWSTemplateFormatVersion: 2010-09-09
Description: Cloudwatch Triggers and rules for running the Twitter Orchestrator

Parameters:
  lambdaARN:
    Type : String
  lambdaName:
    Type : String

Resources:  
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: twitter-orchestrator
      Description: "Cloudwatch Rule for Change of secret values"
      EventPattern: '{
        "source": [
          "aws.ssm"
        ],
        "detail-type": [
          "Parameter Store CChange"
        ],
        "detail": {
          "name": [
            "/prod/twitter/terms"
          ],
          "eventName": [
            "Update",
            "Create"
          ]
        }
      }'
      State: "ENABLED"
      Targets:
        - 
          Arn: !Ref lambdaARN
          Id: cloudWatchTriggerChange

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref lambdaName
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt EventRule.Arn
 

  MaintainenceEventRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "rate(1 hour)"
      State: "ENABLED"
      Targets: 
        - 
          Arn: !Ref lambdaARN
          Id: cloudWatchTriggerMaintainence

  PermissionForMaintainenceEvent: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref lambdaName
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt MaintainenceEventRule.Arn
